"""
SMTP Email Sender
=================
Sends the HTML report via any SMTP server (Gmail, SendGrid, etc.).
Credentials are read exclusively from environment variables — never hardcoded.

Required env vars:
  SMTP_HOST       e.g. smtp.gmail.com
  SMTP_PORT       e.g. 587  (TLS) or 465 (SSL)
  SMTP_USER       your login / sender address
  SMTP_PASSWORD   app-password or API key
  FROM_EMAIL      display sender address (can equal SMTP_USER)
  TO_EMAIL        recipient address (comma-separated for multiple)
"""

from __future__ import annotations

import logging
import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


def _get_env(key: str) -> str:
    val = os.environ.get(key, "").strip()
    if not val:
        raise EnvironmentError(f"Required environment variable '{key}' is not set.")
    return val


def send_report(html_body: str, subject: str) -> None:
    """
    Send the HTML report email.

    Parameters
    ----------
    html_body : str   Full HTML string (generated by report_builder)
    subject   : str   Email subject line
    """
    smtp_host = _get_env("SMTP_HOST")
    smtp_port = int(_get_env("SMTP_PORT"))
    smtp_user = _get_env("SMTP_USER")
    smtp_password = _get_env("SMTP_PASSWORD")
    from_email = _get_env("FROM_EMAIL")
    to_emails = [e.strip() for e in _get_env("TO_EMAIL").split(",")]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = from_email
    msg["To"] = ", ".join(to_emails)

    # Plain-text fallback
    plain_fallback = (
        "Your email client does not support HTML. "
        "Please view this report in a modern email client."
    )
    msg.attach(MIMEText(plain_fallback, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    context = ssl.create_default_context()

    try:
        if smtp_port == 465:
            # SSL from the start
            with smtplib.SMTP_SSL(smtp_host, smtp_port, context=context) as server:
                server.login(smtp_user, smtp_password)
                server.sendmail(from_email, to_emails, msg.as_string())
        else:
            # STARTTLS (port 587 or 25)
            with smtplib.SMTP(smtp_host, smtp_port) as server:
                server.ehlo()
                server.starttls(context=context)
                server.ehlo()
                server.login(smtp_user, smtp_password)
                server.sendmail(from_email, to_emails, msg.as_string())

        logger.info("Report sent successfully to %s", to_emails)

    except smtplib.SMTPAuthenticationError as exc:
        logger.error("SMTP authentication failed: %s", exc)
        raise
    except smtplib.SMTPException as exc:
        logger.error("SMTP error while sending report: %s", exc)
        raise
