import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: 'Key insight',
    noAnalysisSummary: 'No analysis conclusion yet',
    actionAdvice: 'Action suggestion',
    noAdvice: 'No suggestions',
    trendPrediction: 'Trend forecast',
    noPrediction: 'No forecast',
    marketSentiment: 'Market sentiment',
    strategyPoints: 'Strategy levels',
    sniperLevels: 'Sniper levels',
    idealBuy: 'Ideal buy',
    secondaryBuy: 'Secondary buy',
    stopLoss: 'Stop-loss level',
    takeProfit: 'Take-profit target',
    noValue: '—',
    newsFeed: 'News feed',
    relatedNews: 'Related news',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Off',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later for the latest news.',
    openLink: 'Go',
    transparency: 'Opacity',
    traceability: 'Data lineage',
    rawResult: 'Raw analysis result',
    analysisSnapshot: 'Analysis snapshot',
    copy: 'Copy',
    copied: 'Copied',
    recordId: 'Record ID',
    fullReport: 'Full analysis report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown source',
    copyPlainText: 'Copy plain text',
    analysisModel: 'Analysis model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'Sector linkage',
    relatedBoards: 'Related sectors',
    leadingBoard: 'Top gainers',
    laggingBoard: 'Top losers',
    neutralBoard: 'Neutral',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
